### PR TITLE
Enhancing text for Flannel configuration

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>

### CODE REVIEW

**Comment by eparis** [comment]
LGTM

**Comment by LalatenduMohanty** [comment]
@scollier Can please take a look ? if you dont have any review comments , lets merge it.

**Comment by scollier** [comment]
Doh!  My apologies @LalatenduMohanty.

**Comment by LalatenduMohanty** [comment]
@scollier not a problem, thanks :)

**Pull request merged**
